require_relative "boot"

require "rails/all"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Music
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 8.0

    # Please, add to the `ignore` list any other `lib` subdirectories that do
    # not contain `.rb` files, or that should not be reloaded or eager loaded.
    # Common ones are `templates`, `generators`, or `middleware`, for example.
    config.autoload_lib(ignore: %w[assets tasks])

    # Configuration for the application, engines, and railties goes here.
    #
    # These settings can be overridden in specific environments using the files
    # in config/environments, which are processed later.
    #
    # config.time_zone = "Central Time (US & Canada)"
    # config.eager_load_paths << Rails.root.join("extras")

    # Dart Sass compiles app/assets/stylesheets/*.scss into app/assets/builds/.
    # Keep Propshaft from also serving the raw .scss source files publicly.
    config.assets.excluded_paths << Rails.root.join("app/assets/stylesheets")

    # --- Shared UI (centralized helpers/partials/assets across projects) ---
    # One directory on disk that every app reads from. No gem/bundle step:
    # edit the source once, restart the apps, all of them pick it up.
    # Override the location with SHARED_UI_PATH; otherwise auto-discover.
    shared_ui = ENV.fetch("SHARED_UI_PATH") do
      [
        "/var/www/vhosts/ltvb.nl/ui-components",         # server
        File.expand_path("../../ui-components", __dir__) # local checkout next to the app
      ].find { |path| Dir.exist?(path) }
    end

    if shared_ui && Dir.exist?(shared_ui)
      config.paths["app/views"]   << File.join(shared_ui, "views")
      config.paths["app/helpers"] << File.join(shared_ui, "helpers")
      config.assets.paths         << File.join(shared_ui, "assets")

      # The shared assets dir is already on Dart Sass's --load-path (via
      # config.assets.paths above), so compile every shared *.scss into this
      # app's builds dir as <name>.css. Propshaft then serves them for
      # `stylesheet_link_tag "<name>"`. Absolute input paths are kept as-is by
      # dartsass-rails (Pathname#join with an absolute path returns it).
      # Skip Sass partials (`_foo.scss`) — they're @use/@import-only, not builds.
      # Record each built stylesheet's name so the layout can auto-link them
      # (`config.x.shared_stylesheets`) instead of hardcoding `stylesheet_link_tag "ui"`.
      config.x.shared_stylesheets = []
      Dir.glob(File.join(shared_ui, "assets", "scss", "*.scss")).sort.each do |scss|
        next if File.basename(scss).start_with?("_")
        name = File.basename(scss, ".scss")
        config.dartsass.builds[scss] = "#{name}.css"
        config.x.shared_stylesheets << name
      end
    end

    # --- Auto-discover the local stylesheet tree ---
    # Sass has no glob import, so rather than hand-maintaining per-folder
    # _index.scss barrels, generate _manifest.scss with a `@use` for every
    # .scss leaf under app/assets/stylesheets. The committed application.scss
    # just `@use "manifest"`. Add a file anywhere in the tree → next boot
    # regenerates the manifest and it's compiled in. (Variable sharing is
    # unaffected: each leaf pulls its own tokens via `@use "../config" as *`,
    # so the manifest never has to worry about ordering.)
    stylesheets = Rails.root.join("app/assets/stylesheets")
    if stylesheets.directory?
      uses = Dir.glob(stylesheets.join("**/*.scss")).filter_map { |path|
        rel  = Pathname.new(path).relative_path_from(stylesheets)
        name = rel.basename(".scss").to_s
        # Skip the generated manifest, the entrypoint, and folder barrels
        # (_index.scss) — barrels are @use'd by their leaves, not the manifest.
        next if %w[_manifest application _index].include?(name)
        dir = rel.dirname.to_s
        url = (dir == "." ? name.delete_prefix("_") : "#{dir}/#{name.delete_prefix("_")}")
        %(@use "#{url}";)
      }.sort
      File.write(
        stylesheets.join("_manifest.scss"),
        ([ "// AUTO-GENERATED by config/application.rb — do not edit." ] + uses).join("\n") + "\n"
      )
    end
  end
end
